/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertionSort */

#ifndef _Included_InsertionSort
#define _Included_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InsertionSort
 * Method:    runInsertionSort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_InsertionSort_runInsertionSort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
